package handlers

import (
	"net/http"
	"strconv"
	repo "todo-api/internal/repository"

	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type CreateTaskRequest struct {
	Title       string  `json:"title" binding:"required"`
	Description *string `json:"description"`
	Completed   bool    `json:"is_completed"`
}

type UpdateTaskRequest struct {
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Completed   bool    `json:"is_completed"`
}

func CreateTaskHandler(pool *pgxpool.Pool) gin.HandlerFunc {
	return func(c *gin.Context) {
		var input CreateTaskRequest

		// Check if the request body is valid JSON and bind it to the input struct
		if err := c.ShouldBindJSON(&input); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
		}

		task, err := repo.CreateTask(pool, input.Title, input.Description, input.Completed)

		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return
		}

		c.JSON(http.StatusCreated, task)

	}
}

func GetAllTasksHandler(pool *pgxpool.Pool) gin.HandlerFunc {
	return func(c *gin.Context) {
		tasks, err := repo.GetAllTasks(pool)

		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return
		}

		c.JSON(http.StatusOK, tasks)
	}
}

func GetTaskByIdHandler(pool *pgxpool.Pool) gin.HandlerFunc {
	return func(c *gin.Context) {
		taskId := c.Param("id")

		// convert an int or number enclosed in "" to an integer (without the string), e.g. "2" to 2
		id, err := strconv.Atoi(taskId)

		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
		}

		task, err := repo.GetTaskById(pool, id)

		if err != nil {
			if err == pgx.ErrNoRows {
				c.JSON(http.StatusNotFound, gin.H{"error": "Task not found!"})
				return
			}

			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return
		}

		c.JSON(http.StatusOK, task)
	}
}

func UpdateTaskHandler(pool *pgxpool.Pool) gin.HandlerFunc {
	return func(c *gin.Context) {
		taskId := c.Param("id")

		id, err := strconv.Atoi(taskId)

		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid ID provided!"})
			return
		}

		var payload UpdateTaskRequest

		if err := c.ShouldBindJSON(&payload); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
		}

		task, err := repo.UpdateTask(pool, id, payload.Title, payload.Description, payload.Completed)

		if err != nil {
			if err == pgx.ErrNoRows {
				c.JSON(http.StatusNotFound, gin.H{"error": "Task not found!"})
				return
			}

			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		}

		c.JSON(http.StatusOK, task)
	}
}

func DeleteTaskHandler(pool *pgxpool.Pool) gin.HandlerFunc {
	return func(c *gin.Context) {
		taskId := c.Param("id")

		id, err := strconv.Atoi(taskId)

		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid ID provided!"})
			return
		}

		err = repo.DeleteTask(pool, id)

		if err != nil {
			errorMessage := "Task with id " + taskId + "not found!"
			if err.Error() == errorMessage {
				c.JSON(http.StatusNotFound, gin.H{"error": "Task not found!"})
				return
			}

			// check if there was a problem generated by the DB
			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		}

		c.JSON(http.StatusNoContent, gin.H{"message": "Task deleted successfully!"})

	}
}